name: nominatim
version: 0.0.1
author: Matias Meno <m@tias.me>
description: OpenStreetMap Nominatim API.
homepage: https://github.com/enyo/nominatim
documentation: http://enyo.github.com/nominatim/nominatim.html
dependencies:
  xml: ^3.2.3
dev_dependencies:
  test: any
