name: nominatim
version: 0.0.1
author: Matias Meno
description: OpenStreetMap Nominatim API.
homepage: https://github.com/enyo/nominatim
documentation: http://enyo.github.com/nominatim/
dependencies:
  unittest: any
  xml: any
